### ISSUE TITLE
Crash via Thaumic blood knife

### ISSUE THREAD

**Issue by ShadeVahKiin** [MyM-ModpackTeam/ThaumicSkies#14]
So when i was researching through the book, there was a section in artifices with blood magic stuff.  One things was a sacrificial knife, but if you hover over it to see what it is, it crashes the game.
Was able to replicate

**Comment by ShadeVahKiin** [comment]
[crash-2015-12-18_14.57.38-client.txt](https://github.com/MyM-ModpackTeam/ThaumicSkies/files/67093/crash-2015-12-18_14.57.38-client.txt)

**Comment by ShadeVahKiin** [comment]
also happens in nei

**Comment by MaelstromPhx** [comment]
Do you have any additional mods installed like Optifine or Fastcraft?

**Comment by ShadeVahKiin** [comment]
Nope. Using the mym launcher so only other thing i have is journey map

**Comment by MaelstromPhx** [comment]
What operating system are you on?

**Comment by ShadeVahKiin** [comment]
Windows 8

**Comment by kindlich** [comment]
Now closed due to update solving this issue
