### ISSUE TITLE
Opening "Guide to Dimensional Pockets" Crashes You

### ISSUE THREAD

**Issue by Vifury** [MyM-ModpackTeam/ThaumicSkies#15]
I opened the book and it crashed my client. Yes, I use Optifine. Anyone else crash by this?

Error report:
[crash-2015-12-20_18.32.00-client.txt](https://github.com/MyM-ModpackTeam/ThaumicSkies/files/68010/crash-2015-12-20_18.32.00-client.txt)

**Comment by ShadeVahKiin** [comment]
Which mod is the book? Getting on now so I will see.

**Comment by ShadeVahKiin** [comment]
Doesn't crash me, running w/o optifine.

**Comment by kindlich** [comment]
Guess there's no need for this to be open anymore...
