### ISSUE TITLE
Impossible research

### ISSUE THREAD

**Issue by ShadeVahKiin** [MyM-ModpackTeam/ThaumicSkies#16]
So a certain Research in the Gadomancy Tab is un completeable since perditio and telum have to share one slot, any way to change it?
![2015-12-23_12 14 59](https://cloud.githubusercontent.com/assets/16354330/11981243/d9ec8960-a96e-11e5-866c-528159172c25.png)

**Comment by MaelstromPhx** [comment]
Making another note fixes the issue since the hexes are randomized.
