### ISSUE TITLE
Immersive Engineering Wires Disconnecting

### ISSUE THREAD

**Issue by TheIcyOne** [MyM-ModpackTeam/ThaumicSkies#17]
I have found that my LV Wires from Immersive Engineering frequently disconnect, seemingly on server restart. I assume this isn't intended behaviour.

**Comment by MaelstromPhx** [comment]
Hm. I haven't gotten that far but I know chugga was experiencing something similar as well. No clue what could be causing it tho. If one of the staff members has any idea please let me know :3

**Comment by TheIcyOne** [comment]
Seems to occur on other IE servers, too. May be related to MyM, or possibly glitchymod.

**Comment by TheIcyOne** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/160

**Comment by MaelstromPhx** [comment]
I'll update when I can get to console
