### ISSUE TITLE
Warp effect kicks you if you talk in chat

### ISSUE THREAD

**Issue by chuggafan** [MyM-ModpackTeam/ThaumicSkies#18]
There's a warp effect from an addon that is "Your tongue goes numb" and you get kicked when talking in chat, could you somehow disable it?

**Comment by chuggafan** [comment]
Known the mod that does it: Warp theory; please remove, as i have been checking their git and have seen no way to get rid of the warp effect.... please remove the mod, as now i can't talk in chat without a forcekick, thanks

**Comment by bookerthegeek** [comment]
I think it is an amazing feature.

**Comment by chuggafan** [comment]
an amazing feature to be forcefully permanently unable to talk in chat? and oh no, you'll get the thing almost gaurenteed, very little warp needed to trigger it... trust me

**Comment by MaelstromPhx** [comment]
It looks like its supposed to garble the message in chat in the code. I'll talk to the author and see whats up.

**Comment by MaelstromPhx** [comment]
Actually it looks like Wisski may have patched it. If it happens again lemme know.

**Comment by kindlich** [comment]
Please remove that mod!
It deleted some of our blocks in on the IS (no matter whether it was tile entity or not), killed us several times (spawns withers/randomly TP's you around the IS, even into the void), and is just annoying...

It does more harm than good...

**Comment by chuggafan** [comment]
It also swaps blocks with podzol and the like, the mod is a troll, it's annoying, and it ACTUALLY makes warp harmfull... permanently, please, just remove the mod, it's easier than the hassel of patching a mod that's been abandoned

**Comment by chuggafan** [comment]
THIS is the FINAL straw, this mod NEEDS IMMEDIATE removal THE MOD just DID this to my base: https://imgur.com/a/Jia3q
