### ISSUE TITLE
[Bug] Error Switching from Multiplayer to Singleplayer

### ISSUE THREAD

**Issue by MaelstromPhx** [MyM-ModpackTeam/ThaumicSkies#2]
When joining a multiplayer server and then trying to start/continue a single player world it kicks the player back to the start screen. Something to do with Minetweaker/Modtweaker Pulverizer recipe handling.

http://paste.ee/p/mW4ol

**Comment by Slind14** [comment]
What about connecting to the single player twice.

**Comment by MaelstromPhx** [comment]
Creating a world/joining a world works and then rejoining works as well. However if you leave a world and try to create a new one it has the same effect.

**Comment by Slind14** [comment]
This is a long standing bug which many many packs have including, gs, hypo, ag, regrowth..

**Comment by MaelstromPhx** [comment]
Guess there's nothing we can really do about it then. I'll close this then
