### ISSUE TITLE
Passive Mobs despawn immediately

### ISSUE THREAD

**Issue by TheIcyOne** [MyM-ModpackTeam/ThaumicSkies#20]
When spawning chickens using spawn eggs, the egg is consumed but the chicken does not spawn.
This precedes my previous egg farm, the chickens from which also despawned. This is likely due to the hostile and passive mobs sharing the same cap.

**Comment by MaelstromPhx** [comment]
I believe that is a server side issue for MyM specifically. I'd make a post on the MyM forum for that.
