### ISSUE TITLE
Portal Stops working

### ISSUE THREAD

**Issue by danny-janse** [MyM-ModpackTeam/ThaumicSkies#22]
# Portal Stops Working

Portals stop working from time to time.
## Cause

Whenever the server restarts or crashes (basicly the boot of the server.)
## Solution

Replacing the sign underneath the portal.

ps: This does not only apply to ThaumicSkies but some other modpacks aswell.

**Comment by Sir-Will** [comment]
This should be reported in the MyM forum as this is related to the server and not modpack but I will look into it.

**Comment by Sir-Will** [comment]
Just tried to reproduce this and the sign did still work after an server restart.
If you still have the issue please create a forum thread.
