### ISSUE TITLE
Primordial Pearl

### ISSUE THREAD

**Issue by Zxirl** [MyM-ModpackTeam/ThaumicSkies#23]
Currently there is only one way to get a primordial pearl: Rare Thaumcraft bags... Which a not only rare, but have an extremely low drop rate for primordial pearls.

The gadomancy portal to the outer lands doesn't work.

Suggestion: add a recipe for the 9x9 to create pearls or 3x3 something that is semi-endgame but not stupid hard to make. :) your other recipes look great im sure you will come up with a good alternative.

**Comment by MaelstromPhx** [comment]
Yeah the portal doesn't work because its not the overworld :/

I'll get something up as soon as I have console access soon.

**Comment by kindlich** [comment]
I'm closing this issue, as there is a way to get the pearls now
