### ISSUE TITLE
Angel Ring [5073] - Impossible to craft

### ISSUE THREAD

**Issue by Zxirl** [MyM-ModpackTeam/ThaumicSkies#24]
The Angel Ring currently cannot be crafted. The only way to get "Cloud - 1289" is to use cloud in a bottle which is a banned item (can be use to grief).

Could you please modify the recipe to require something other than clouds or add a recipe for clouds. :+1:

**Comment by MaelstromPhx** [comment]
:/
I'll fix it :P

**Comment by kindlich** [comment]
Closed due to being fixed now
