### ISSUE TITLE
Wrench Module - Recipe Fix

### ISSUE THREAD

**Issue by CobblePi** [MyM-ModpackTeam/ThaumicSkies#31]
Hey ho,

 wanted to tell you guys about this "broken" recipe:

https://imgur.com/HArwNaZ

The current recipe is using Fire, which you can't acquire (i think). My Suggestion is to eventually replace the fire with blaze powder. The item is from the Omni-Stuff Mod.

 -CobblePi

**Comment by kindlich** [comment]
Was fixed in #30
