### ISSUE TITLE
Server Glitches

### ISSUE THREAD

**Issue by Bluberrysoda** [MyM-ModpackTeam/ThaumicSkies#36]
I don't know if I should report this on here or the Mym forums but the server has glitches a couple of times and deleted my items. The first time was when I broke a grave near a portal in the nether and some of my items went through the portal and totally disappeared when I tried to get them. The main thing I lost was an Essential Dynamo from Thaumic Horizons. So I made another one. It wasn't working right, so I would brake it, wait for essential to build up, and then replace it. So I did this one time when it was lagging but the Dynamo totally vanished. If possible, I'd really like another one.

**Comment by kindlich** [comment]
This is no pack-related issue, just open a /ticket for that
