### ISSUE TITLE
Pyrophobic Coating bug

### ISSUE THREAD

**Issue by Bluberrysoda** [MyM-ModpackTeam/ThaumicSkies#37]
So I decided to try out the pyrobhopic coatings on the steam exosuit shoes from Flaxbeard's steam power to help me mine and find nodes in the nether. I tried to test them by jumping in the lava. Now any time I get on I'm stuck in an "Internal Server Error" loop.

**Comment by kindlich** [comment]
That's FSP's fault... Sorry, I can't do anything about it.

However, I could confirm that this happens on servers, as the same happened to me on a local server just now!
Created an issue on FSP's github page
https://github.com/Esteemed-Innovation/Flaxbeards-Steam-Power/issues/455

Until then, just ask create a /ticket (you can do that from the HUB) and ask an admin to tp you back to spawn
