### ISSUE TITLE
Hiveacynth recipe

### ISSUE THREAD

**Issue by jackie-sh** [MyM-ModpackTeam/ThaumicSkies#40]
It is impossible to create a hiveacynth. It should have a recipe with 4 Mana Powders as seen in the botania book. Instead NEI shows as needing 4 Ender Air Bottles. It is impossible to throw in the bottles as the petal apothecary does not accept those. I do not know which way is it supposed to be but currently neither is working.
NEI recipe ![1](https://cloud.githubusercontent.com/assets/7189409/17651345/91e9424c-6265-11e6-8036-d0ac167d9a38.PNG) Botania recipe ![2](https://cloud.githubusercontent.com/assets/7189409/17651344/91e8da5a-6265-11e6-83b5-5d3dd62d4be1.PNG)

**Comment by kindlich** [comment]
It could be caused by a botania update a while ago. There once where mana petals, and manaresource:15 was most likely one of those back then...
Almost fixed
