### ISSUE TITLE
Things so far...

### ISSUE THREAD

**Issue by ChipRoger** [MyM-ModpackTeam/ThaumicSkies#6]
Its very very very very grindy trying to get the 7 ingots and 10 nuggets of iron from compressed cobble.  On average thats 73x9x4... 292x9.... 18+810+1800.... 2,628 cobble average needed to be mined to getting in the required iron for the thaumcraft crucible.  Very slow with a flint pickaxe.

Second issue... we decided based off this to build an item transfer node with a world interaction upgrade for a cobble gen to save some time only to find for some reason the node doesnt want to pick up the cobble.  Not sure what that was about.  If someone else could test it on their island let us know if its an issue.

**Comment by Bennyboy1695** [comment]
it isnt an issue, the cobblegen feature of the transfer node has been disabled in the configs

**Comment by ChipRoger** [comment]
aha, does the same hold true for the open blocks block breaker?  Since thet also does not work.

**Comment by Sandstroem** [comment]
Yeah, I agree. This pack is centered around Thaumcraft and it takes ages to actually get into it.
Alternatives for cobble gen would be Igneous Extruder and some other block breakers, all that require certain metals. Cobble is not just required for the first Nuggets, but also to build out some platforms, unless you want keep living on wooden platforms.

Even the not working Transfer Node with the World Upgrade needs 7 iron, which is not much less than the amount calculated above.

And of course the calculation doesnt include the sand, gravel and dust you have to get for all the clay, redstone, glass, lava and stuff you additionally need.

**Comment by ChipRoger** [comment]
let's see...  Crucible+wand... 7 ingots+10 nuggets wand... 8 1/7 iron
World upgrade+transfer node: 7 ingots+4 lapis +11 redstone
block breaker - OB: 3 diamonds at 1% drop rate+1 redstone torch (cheapest option so far) - doesn't work
SFM block gate, method: 11 iron, 11 redstone, 4 gold.  Most expensive.

All have equally long methods of reaching so far, which is a very long time.  Currently it looks like the quickest method of getting basic iron is 11 obsidian for nether portal+obsidian pick and get everything in the nether (unless ore gen is off in there).

A suggestion to fix I can think of to encourage Crucible use and allow a slightly less insanely grindy method of reaching beginner Thaumcraft access would be either tweak thaumcraft crucible recipe to only require the ex nihilo crucible and wand to make, or if easier, tweak the vanilla cauldron recipie to a less metal dependant recipie.  Such as, I dunno...  stone, with iron ingots down the the middle to simulate metal lining?  Something like that.

**Comment by Sandstroem** [comment]
U shape. Replace 2 left and right with nuggets. 3 ingots on the floor. Makes 3 ingots and 4 nuggets. Basically half than now. Enable the automated Cobblestone gen.

**Comment by ChipRoger** [comment]
Just spent 5 hours, and 12 obsidian picks trying to get iron...  I have a mighty 2 ingots.  Far far far far too slow to get a crucible to even start making anything like quicksilver, silverwood, greatwood.

**Comment by ChipRoger** [comment]
Also you may need some sort of 'opse!' backup for the new island players.  If before you have a crucible you fall off your island holding your thaumometer, you have zero chance of getting a replacement until you have a crucible.  Fall off with your flower too, and that really wont be a fun time.  No source of aspects at all then.  If they havent unlocked ores of the deconstruction table in the research table yet...

**Comment by MaelstromPhx** [comment]
I've thought about how to make the needed early game items more accessible but haven't really been able to find a good solution. The thaumometer, googles and flower are pretty simple items but at the same time aren't supposed to be free, since that can easily be abused. So far my solution is just to add a tip to the thaumonomicon or online guide about not wearing/carrying them unless you really need them. Another point is that the graves spawn at y level 2 or 3 so getting the items back is just a matter of being able to skyblock your way down. 

As for the crucible/cobble recipes I would be okay with reducing the iron cost a little. Each iron ingot is equivalent to 81 cobblestone which is 567 cobble total as of right now. I'm thinking of reducing it down to probably 5 ingots in a U which cuts the cost down to 405. I don't think that's too unreasonable, especially considering the ease of getting iron afterwards via the crucible.

**Comment by Sandstroem** [comment]
Yeah, after you set the drop rate of Nuggets back to 100%, this looks totally different. Might even be okay to keep the normal Crucible Recipe. 7*81 = 567 Cobble is just 8,5 stacks or so. Not really needed to change something here. Plus another 1,5 stacks for the wand.

**Comment by MaelstromPhx** [comment]
Yeah sorry about that. I thought I had it set to 100% but apparently not XD

**Comment by TheIcyOne** [comment]
It is also possible to just melt down iron armour and tools from drops using the Alloy Smelter.

**Comment by Bennyboy1695** [comment]
Smeltery is what is used for melting down armour and tools, and as for the iron situation i had no trouble getting iron, people forget that zombies can drop them aswell as they can come in the lootbags. Thats how i got my first lot of iron was from zombies and bags. I also used obsidian from a loot bag to create a high tiered pick with tinkers without even needing the smeltery

**Comment by MaelstromPhx** [comment]
Yeah both those methods are valid. There is a standard way to do it with the compressed cobble, but if you find a faster way that suits you thats fine too :P

**Comment by ChipRoger** [comment]
We got what we needed and once the crucible is up, its all nice and easy.  Just thought that initial tiny step could use a tiny tweak.  I have noticed an odd problem with using chiseled sandstone for perditio and preacantio.  If you throw in 1, you get 3 and 1, but the next 3 break down into 4 sand due to that...  new decompose thingy costing you 1 perditio.  Quite amusing trying to use it to make tainted soil stuff to make saplings. you have to throw in 4 blocks to get 1 preacantio and no perditio before you can add a second praecantio and 3 perditio again. Wish I'd had netherwart.  I was wondering if you could keep it working for basic sandstone but disable is for chiseled sandstone?  Sources of praecantio are somewhat sparse.

```
 On Sunday, 13 December 2015, 12:49, MaelstromPhx <notifications@github.com> wrote:
```

 Yeah both those methods are valid. There is a standard way to do it with the compressed cobble, but if you find a faster way that suits you thats fine too :P—

**Comment by MaelstromPhx** [comment]
That's part of the challenge :smiley: You have to find good sources of praecantantio like nether wart or something creative like Botania flowers. It wouldn't be fun if it was easy

**Comment by MaelstromPhx** [comment]
Gonna close since nothing has been said in a while
