### ISSUE TITLE
Clay bucket doesnt work with the sink

### ISSUE THREAD

**Issue by Sandstroem** [MyM-ModpackTeam/ThaumicSkies#7]
Might be intended, but the clay bucket doesnt work with the sink we get at the start. Probably because it is from Ex Nihilo and not integrated.

We crafted Water bottles and used those to get water from sink to barrels. And there is enough rain anyway. But maybe changing that might be nice.

**Comment by MaelstromPhx** [comment]
I noticed that. I believe it is an issue with how the sink is coded to provide water. As of right now I have no fix but a workaround is to use a water bottle to transfer water from the sink to barrel and then just use the buckets to get it out of the barrel.

**Comment by chaosblad3** [comment]
Or, you know, you could have asked me or wisski to fix it for you with commandhelper.. like i just did ;)

**Comment by Bennyboy1695** [comment]
CommandHelper doesn't fix single player though ;)

**Comment by chaosblad3** [comment]
Pfft serves them right for not playing on our server instead then doesn't it :P

**Comment by chaosblad3** [comment]
A minetweaker alternative workaround that would work in singleplayer could be:

```
recipes.addShapeless(<IguanaTweaksTConstruct:clayBucketWater>, [<IguanaTweaksTConstruct:clayBucketFired>, <harvestcraft:sink:*>.reuse()]);
```

So crafting an empty clay bucket with a sink would give back a filled bucket and leave the sink in the crafting grid, though that does seem kinda counter-intuitive as it makes buckets of water essentially autocraftable.. i'll leave that one up to you!

**Comment by MaelstromPhx** [comment]
Patched
