### ISSUE TITLE
Botania Mana gen flowers

### ISSUE THREAD

**Issue by miner-bob-1960** [MyM-ModpackTeam/ThaumicSkies#8]
the recipe of nitor, glowstone and a torch, dose not work to create the Daybloom, all items just land on the floor when trying to put them in the petal apothecary.

**Comment by TheIcyOne** [comment]
Have you tried using the original recipe?

**Comment by miner-bob-1960** [comment]
Yes, the petals go into the apothecary, but nothing happens when you ad the seed.

**Comment by MaelstromPhx** [comment]
I'll look into it. I'm thinking the apothecary might not support items from other mods but I'll do some testing to make sure.

**Comment by MaelstromPhx** [comment]
Seems the petal apothecary only accepts items listed as petals or mana resources. I'll have to find a new recipe then.

**Comment by MaelstromPhx** [comment]
Reverted the recipes to normal and added one for podzol. Should be obtainable now.
